---
sudo: false

language: php

php:
  - '5.6'
  - '7.0'

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --no-progress
  - vendor/roundpartner/configuration/bin/set_configs_permission.sh

script:
  - vendor/bin/phpunit
...