---
sudo: false

language: php

php:
  - '5.6'
  - '7.0'

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --no-progress --no-autoloader
  - composer dumpautoload --no-interaction --optimize
  - vendor/roundpartner/configuration/bin/set_configs_permission.sh
  - cat vendor/composer/autoload_classmap.php

script:
  - vendor/bin/phpunit
...