---
services:
  config:
    class: \RoundPartner\Deploy\Config
    arguments: ['config.example.ini']
  logger:
      class: \Monolog\Logger
      arguments: ['file']
      calls:
        - [pushHandler, ['@applog']]
  applog:
    class: Monolog\Handler\StreamHandler
    arguments: ['/tmp/deploy.log', 'INFO']
  maker:
    class: RoundPartner\Maker\Maker
...