services:
  config:
    class: \RoundPartner\Deploy\Config
  logger:
    class: \Monolog\Logger
    arguments: ['file']
    calls:
      - [pushHandler, ['@applog']]
  applog:
    class: Monolog\Handler\StreamHandler
    arguments: ['/var/log/deploy.log', 'INFO']
