---
services:
  config:
    class: RoundPartner\Deploy\Config
  logger:
    class: Monolog\Logger
    arguments: ['file']
    calls:
      - [pushHandler, ['@applog']]
  applog:
    class: Monolog\Handler\StreamHandler
    arguments: ['/var/log/deploy.log', 'INFO']
  maker:
    class: RoundPartner\Maker\Maker
  pigeon:
    class: RoundPartner\Pigeon\Pigeon
    arguments: ['http://rumia:3411']
  runner:
    class: RoundPartner\Deploy\Runner
    arguments: ['@logger']
...