---
services:
  config:
    class: RoundPartner\Deploy\Config
    arguments: ['config.example.ini']
  logger:
      class: Monolog\Logger
      arguments: ['file']
      calls:
        - [pushHandler, ['@applog']]
  applog:
    class: Monolog\Handler\StreamHandler
    arguments: ['/tmp/deploy.log', 'INFO']
  maker:
    class: RoundPartner\Test\Mocks\Maker
  pigeon:
    class: RoundPartner\Test\Mocks\Pigeon
    arguments: ['http://localhost:3411']
  seq:
    class: RoundPartner\Seq\Seq
    arguments: ['chen', 'an example key']
  runner:
    class: RoundPartner\Test\Mocks\RunnerMock
    arguments: ['@logger']
...